server:
    port: 8084

spring:
    application:
        name: event-service
    cloud:
        config:
            uri: http://localhost:8888/
        consul:
            host: localhost
            discovery:
                port: 8084
                instance-id: ${spring.application.name}:1
                service-name: event-service

my:
    test:
        value: Newly refreshed hello from server local


