server:
  port: 8081

spring:
  application:
    name: product-service
  cloud:
    consul:
      host: localhost
      discovery:
        port: 8081
        instance-id: ${spring.application.name}:1
        service-name: product-service

