server:
  port: 8082

spring:
  application:
    name: promotion-service
  cloud:
    consul:
      host: localhost
      discovery:
        port: 8082
        instance-id: ${spring.application.name}:1
        health-check-path: /health-check
        health-check-interval: 20s
        service-name: promotion-service



