server:
    port: 8080

spring:
    application:
        name: storefront-service
    cloud:
        config:
            uri: http://localhost:8888/
        consul:
            host: localhost
            discovery:
                port: 8080
                instance-id: ${spring.application.name}:1
                health-check-path: /health-check
                health-check-interval: 20s
                service-name: storefront-service


my:
    test:
        value: Hello from server local


